### ISSUE TITLE
Missing power off icon.

### ISSUE THREAD

**Issue by alu18999959g** [CQQL/lightdm-webkit-theme-nebel#1]
Hi, i'm Archlinux user and i have installed your lightdm-webkit-theme. I have noticed that power off icon is missing on the greeter. Restart, Suspend and Hibernate are present on the greeter but power off is missing. My Desktop Environmment is Cinnamon 2.4.6 and gtk 3.14.

Regards.

**Comment by martenlienen** [comment]
Thanks for your feedback. I already noticed this, but I could not find out, what caused it. But I just noticed, that lightdm-webkit calls it [shutdown](http://bazaar.launchpad.net/~lightdm-team/lightdm-webkit-greeter/trunk/view/head:/src/lightdm-webkit-greeter.c#L908) instead of [power off](https://github.com/CQQL/lightdm-webkit-theme-nebel/blob/969ed8b13623da3ce2debf92d27306b8742713ba/src/buttons.js#L79).

I will push a fix in the next few minutes.
